version: "3.8"
name: server
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: box4kids
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 80M
        reservations:
          memory: 40M

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 25M

  api:
    build: .
    ports:
      - "8000:8000"
    user: "1000:1000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/box4kids
      REDIS_URL: redis://redis:6379
      DEBUG: "true"
      SECRET_KEY: "dev-secret-key-change-in-production"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/venv
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 150M

volumes:
  postgres_data:
  redis_data:
